### ISSUE TITLE
Attempt to free invalid pointer

### ISSUE THREAD

**Issue by yurivict** [kcat/openal-soft#134]
I am trying to run an example using google perftools malloc library, and am getting this crash:

```
$ LD_PRELOAD=/usr/local/lib/libtcmalloc_minimal.so /usr/local/bin/alloopback
src/tcmalloc.cc:302] Attempt to free invalid pointer 0x804816000 
Abort trap
```

Stack trace from inside google-perftools shows this:
```
Obtained 6 stack frames.
0x80083564b <tc_set_new_mode+0x3fb> at /usr/local/lib/libtcmalloc_minimal.so
0x8010eccf5 <alcResetDeviceSOFT+0x16af5> at /usr/local/lib/libopenal.so.1
0x8010bc3d6 <alProcessUpdatesSOFT+0x276> at /usr/local/lib/libopenal.so.1
0x8010b27de <alGenSources+0xbe> at /usr/local/lib/libopenal.so.1
0x402665 <main+0x4a5> at /usr/local/bin/alloopback
0x40205f <_start+0x17f> at /usr/local/bin/alloopback
```

Same problem with qTox (it uses openal).

Version 1.17.2 on FreeBSD.

**Comment by kcat** [comment]
> Version 1.17.2 on FreeBSD.

Please try the latest Git version, or at least 1.18.0. That stack trace is also a bit nonsense, so if it still happens in the newer version, you may need to make a debug build of OpenAL Soft.

**Comment by yurivict** [comment]
In 1.18.0 I am getting:

```
$ LD_PRELOAD=/usr/local/lib/libtcmalloc.so.4 /usr/local/bin/alloopback
Obtained 9 stack frames.
0x80083a70b <tc_set_new_mode+0x58b> at /usr/local/lib/libtcmalloc.so.4
0x8010c00e5 <_init+0x8b5> at /usr/local/lib/libopenal.so.1
0x8010c12c7 <_init+0x1a97> at /usr/local/lib/libopenal.so.1
0x8010c370d <alGetAuxiliaryEffectSlotfv+0x15d> at /usr/local/lib/libopenal.so.1
0x8010ee6cd <alcOpenDevice+0x226d> at /usr/local/lib/libopenal.so.1
0x80137b268 <pthread_once+0xd8> at /lib/libthr.so.3
0x8010c07bd <_init+0xf8d> at /usr/local/lib/libopenal.so.1
0x8010ef575 <alcLoopbackOpenDeviceSOFT+0x25> at /usr/local/lib/libopenal.so.1
0x402601 <main+0x341> at /usr/local/bin/alloopback
src/tcmalloc.cc:302] Attempt to free invalid pointer 0x804c1c000 
```

**Comment by yurivict** [comment]
Debugger shows the stack very nicely:

playback.Device = alcLoopbackOpenDeviceSOFT(NULL); @ main
-> DO_INITCONFIG(); @ alcLoopbackOpenDeviceSOFT
-> alcall_once
-> init_routine(); @ _pthread_once
-> InitEffectFactoryMap(); @ alc_initconfig
-> InsertUIntMapEntry(&EffectStateFactoryMap, AL_EFFECT_COMPRESSOR, ALcompressorStateFactory_getFactory); @ InitEffectFactoryMap
-> al_free(map->keys); @ InsertUIntMapEntry
-> al_free -> free

**Comment by kcat** [comment]
Does Google's perftools malloc library understand the C11 ```aligned_alloc``` function? Or ```posix_memalign```, depending on what was detected by CMake? Seems like a "real" libc allocation function is being called behind tcmalloc's back, so when the pointer is later given to tcmalloc's ```free```, it doesn't recognize it.

**Comment by yurivict** [comment]
Yes, google routinely uses perftools for large projects like chrome and tensorflow.

**Comment by kcat** [comment]
> No, 'real' malloc isn't called.

I said allocation function, not necessarily ```malloc```. There is also C11's ```aligned_alloc```, POSIX's ```posix_memalign```, and others. And if tcmalloc doesn't handle whichever allocation function OpenAL Soft is using, tcmalloc's ```free``` won't recognize the pointers given to it, which seems to be what's happening.

**Comment by yurivict** [comment]
You are right. Perftools doesn't yet handle ```aligned_alloc```, and you use it.

Thank you for your explanation.

**Comment by Techwolf** [comment]
I am getting the same problem. Troubleshooting right now, but I will post this while doing troubleshooting.

```
2017-08-03T00:23:53Z INFO: llaudio/llaudioengine.cpp(133) : init: LLAudioEngine::init() AudioEngine successfully initialized
src/tcmalloc.cc:284] Attempt to free invalid pointer 0x3c84420 

Thread 1 "do-not-directly" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
58      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
#1  0x00007ffff0166e89 in __GI_abort () at abort.c:89
#2  0x00007ffff1d7f773 in tcmalloc::Log (mode=mode@entry=tcmalloc::kCrash, filename=filename@entry=0x7ffff1d95eae "src/tcmalloc.cc", line=line@entry=284, a=..., b=..., c=..., d=...) at src/internal_logging.cc:118
#3  0x00007ffff1d738a7 in (anonymous namespace)::InvalidFree (ptr=<optimized out>) at src/tcmalloc.cc:284
#4  0x00007ffff5db0468 in alstr_append_cstr (str=str@entry=0x7fffffff9648, from=from@entry=0x7ffff5dcbc55 "/alsoft.conf") at /var/tmp/portage/media-libs/openal-1.18.0/work/openal-soft-1.18.0/Alc/helpers.c:1076
#5  0x00007ffff5da3c39 in ReadALConfig () at /var/tmp/portage/media-libs/openal-1.18.0/work/openal-soft-1.18.0/Alc/alcConfig.c:507
#6  0x00007ffff5d9752d in alc_initconfig () at /var/tmp/portage/media-libs/openal-1.18.0/work/openal-soft-1.18.0/Alc/ALc.c:937
#7  0x00007ffff72e7431 in __pthread_once_slow (once_control=0x7ffff6003740 <alc_config_once>, init_routine=0x7ffff5d973f8 <alc_initconfig>) at pthread_once.c:116
#8  0x00007ffff72e74d5 in __GI___pthread_once (once_control=once_control@entry=0x7ffff6003740 <alc_config_once>, init_routine=init_routine@entry=0x7ffff5d973f8 <alc_initconfig>) at pthread_once.c:143
#9  0x00007ffff5d98ddc in alcall_once (callback=0x7ffff5d973f8 <alc_initconfig>, once=0x7ffff6003740 <alc_config_once>) at /var/tmp/portage/media-libs/openal-1.18.0/work/openal-soft-1.18.0/common/threads.h:204
#10 alcOpenDevice (deviceName=deviceName@entry=0x0) at /var/tmp/portage/media-libs/openal-1.18.0/work/openal-soft-1.18.0/Alc/ALc.c:3809
#11 0x00007ffff5b6eb2f in alutInit (argcp=argcp@entry=0x0, argv=argv@entry=0x0) at /var/tmp/portage/media-libs/freealut-1.1.0-r3/work/freealut-1.1.0/src/alutInit.c:67
#12 0x00000000019e80df in LLAudioEngine_OpenAL::init (this=<optimized out>, num_channels=<optimized out>, userdata=<optimized out>) at /usr/src/debug/games-simulation/firestorm-hg-25/linden/indra/llaudio/llaudioengine_openal.cpp:60
#13 0x000000000141287f in idle_startup () at /usr/src/debug/games-simulation/firestorm-hg-25/linden/indra/newview/llstartup.cpp:983
#14 0x00000000009c806f in LLAppViewer::idle (this=this@entry=0x3c22000) at /usr/src/debug/games-simulation/firestorm-hg-25/linden/indra/newview/llappviewer.cpp:5726
#15 0x00000000009caa5f in LLAppViewer::frame (this=0x3c22000) at /usr/src/debug/games-simulation/firestorm-hg-25/linden/indra/newview/llappviewer.cpp:1677
#16 0x00000000005e68d9 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/games-simulation/firestorm-hg-25/linden/indra/newview/llappviewerlinux.cpp:169
```

**Comment by yurivict** [comment]
@Techwolf No need to troubleshoot: https://github.com/gperftools/gperftools/issues/909

**Comment by Techwolf** [comment]
Thanks for the tip. I though tcmalloc was NOT google...my bad. Now I have two places to try downgrading to temp fix this on my system. The above code was working untill I did a system upgrade that upgraded a few packages.
