### ISSUE TITLE
'Illegal instruction' of my C program with openal functions inside

### ISSUE THREAD

**Issue by gdsa1022** [kcat/openal-soft#266]
Hi! few months ago i download a program in C language with openal functions that reproduces a sound that moves randomly through the 3D audio space.
It worked in my computer with the gcc compiler of Sublime Text 3 but once put into the Raspbian Stretch Lite version of 13th of November 2018, it gave me an **Illegal Instruction** error when running it.
Later I installed the gdb debugger to see which are the errors of the code, after running it and making a backtrace appeared me that:

`(gdb) backtrace
#0  Mix_Neon (data=0x34810, OutChans=2, OutBuffer=<optimized out>,
    Gains=Gains@entry=0xa512c070, Counter=0, OutPos=OutPos@entry=0,
    BufferSize=BufferSize@entry=1024) at ./Alc/mixer_neon.c:128
#1  0xb6f436b0 in MixSource (voice=voice@entry=0xa512c020,
    Source=<optimized out>, Device=Device@entry=0xa59fed94,
    SamplesToDo=SamplesToDo@entry=1024) at ./Alc/mixer.c:552
#2  0xb6f33e30 in aluMixData (device=0xa59fed94, device@entry=0x2dc50,
    buffer=0x1000, buffer@entry=0xb1bb4028, size=2) at ./Alc/ALu.c:1466
#3  0xb6f4cf08 in ALCpulsePlayback_mixerProc (ptr=0x2a4a0)
    at ./Alc/backends/pulseaudio.c:835
#4  0xb6cf6fc4 in start_thread (arg=0xa59ff460) at pthread_create.c:335
#5  0xb6e20bc8 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:76
   from /lib/arm-linux-gnueabihf/libc.so.6
`
PD: also i've installed all the openal-soft libraries per Raspbian Stretch Lite (Version 1.17.2-4).

If any of you have any ideas about what is causing the problem (Acces to the code [here](https://github.com/gdsa1022/TFG_HRTF/blob/master/footsteps.c) ) it would be helpful.

**Comment by kcat** [comment]
1.17.2 is pretty old. I'd suggest updating to 1.19.1 if possible, or at least 1.18.2.

From the backtrace, it would seem the library is trying to use NEON extensions but the CPU doesn't like that. NEON should be pretty ubiquitous among modern ARM CPUs though. If your CPU doesn't support it, and the library was built with NEON support, a run-time check wasn't added until 1.18 so it would try to use it anyway. If your CPU does support NEON, then something else is wrong.
